### ISSUE TITLE
Undefined column Target_Role_Primary_Key_Physical_Name

### ISSUE THREAD

**Issue by universe-designer** [ScalefreeCOM/turbovault4dbt#24]
I receive following error of the column Target_Role_Primary_Key_Physical_Name which does not exist in the excel file nor in the model.

Starting Script.
Traceback (most recent call last):
  File "turbovault4dbt\turbovault_excel.py", line 117, in <module>
    main()
  File "lib\site-packages\gooey\python_bindings\gooey_decorator.py", line 134, in <lambda>
    return lambda *args, **kwargs: func(*args, **kwargs)
  File "turbovault4dbt\turbovault_excel.py", line 80, in main
    hub.generate_hub(cursor,source, generated_timestamp, rdv_default_schema, model_path)
  File "turbovault4dbt\procs\sqlite3\hub.py", line 121, in generate_hub
    source_models = generate_source_models(cursor, hub_id)
  File "turbovault4dbt\procs\sqlite3\hub.py", line 47, in generate_source_models
    cursor.execute(query)
sqlite3.OperationalError: no such column: **h.Target_Role_Primary_Key_Physical_Name**

I assume this is some kind of search and replace typo.

**Comment by universe-designer** [comment]
This [Pull Request](https://github.com/ScalefreeCOM/turbovault4dbt/pull/27), solves this problem besides having other features.
